### ISSUE TITLE
Add awscli commands to delete volumes in eks-guide

### ISSUE THREAD

**Issue by nikever** [sighupio/fury-getting-started#2]
In the teardown phase of the eks guide
https://github.com/sighupio/fury-getting-started/blob/main/fury-on-eks/README.md#step-6---teardown. When you delete a cluster via Terraform, the Volumes created are not automatically deleted in AWS.

I think we need to add the commands to delete the volumes as we did for the autoscaler and targets groups.

Probably it's best to group all commands in a single script.

**Comment by ralgozino** [comment]
[Fix is live in the site](https://docs.kubernetesfury.com/docs/quickstart/fury-on-eks/#step-6---teardown)
