### ISSUE TITLE
Add aks getting started guide

### ISSUE THREAD

**Issue by niccoloraspa** [sighupio/fury-getting-started#3]
We should add a getting started guide for fury on Azure that uses https://github.com/sighupio/fury-aks-installer 

The guide should be something similar to the one for EKS: https://github.com/sighupio/fury-getting-started/tree/main/fury-on-eks

The old docs for AKS could be useful http://kfd-docs-fury-1.7-docs.surge.sh/docs/installers/managed/aks/

**Comment by ralgozino** [comment]
As per our call with @smerlos, we decided to go on with the guide using Terraform without the integration with Furyctl (which is currently missing) being that we will need to create the boiler plate anyway.

We can then keep improving the guide later on.

Let's create a `fury-on-aks` folder in the getting started repository, like we do for the other guides, and use that folder to provide the needed boiler plate for the guide.
