### ISSUE TITLE
Update getting started guides for Fury 1.23 

### ISSUE THREAD

**Issue by niccoloraspa** [sighupio/fury-getting-started#4]
As per the title, we should update getting started guides for Fury 1.23.

**Comment by nikever** [comment]
It would be useful to tag the getting started guides with the appropriate Fury version for easy reference:

```bash
git tag ... 
```

**Comment by ralgozino** [comment]
Guides that should be updated:
- [ ] Fury on EKS
- [ ] Fury on GKE
- [x] Fury on Minikube

**Comment by ralgozino** [comment]
Minikube guide update done by @alessandrolomanto in #7
